services:
  backend:
    build: .
    ports:
      - "1234:1234"
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"