services:  
  backend:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: chatapp
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"